/* eslint-disable @typescript-eslint/consistent-type-assertions */
/**
 * Vite configuration for lark-homepage documentation site.
 *
 * Routes are auto-generated by @lark.js/docs defineConfig() —
 * no manual generateRoutesFile() needed here.
 */
import { defineConfig, type PluginOption, type UserConfigFn } from "vite";
import { resolve } from "node:path";
import { larkDocsPlugin } from "@lark.js/docs/vite";
import { larkMvcPlugin7 } from "@lark.js/mvc/vite";
import tailwindcss from "@tailwindcss/vite";
import docsConfig from "./lark-docs.config.js";

const PKG_DIR = import.meta.dirname;

// === Mode router ===

export default defineConfig((({ mode, command }) => {
  const isDev = mode === "development" || command === "serve";
  return {
    /**
     * 'serve': during dev (`vite` command)
     * 'build': when building for production (`vite build` command)
     */
    base: isDev ? "/" : "/lark-cli/",
    root: resolve(PKG_DIR, "app"),
    plugins: [
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      larkDocsPlugin({ config: docsConfig }) as PluginOption,
      larkMvcPlugin7({
        debug: true,
      }) as PluginOption,
      tailwindcss() as PluginOption,
    ],
    resolve: {
      alias: {
        "@lark-docs/generated": resolve(PKG_DIR, ".lark-docs/generated"),
      },
    },
    build: {
      outDir: resolve(PKG_DIR, "dist"),
      emptyOutDir: true,
    },
    server: {
      port: 3300,
      open: true,
    },
  };
}) satisfies UserConfigFn);
