/* eslint-disable @typescript-eslint/no-unused-vars */
import type { LLMClient, MaxTokensSetter } from "../llm/client.js";
import type { ConversationManager, ToolUseBlock, ToolResultBlock } from "../conversation/conversation.js";
import type { ToolRegistry } from "../tools/registry.js";
import type { PermissionChecker, Decision } from "../permissions/checker.js";
import type { HookEngine, EventName } from "../hooks/hooks.js";
import type { FileHistory } from "../file-history/file-history.js";
import type { FileStateCache } from "../tools/file-state-cache.js";
import type { AgentEvent } from "./events.js";
import { StreamingExecutor } from "./streaming-executor.js";
import { manageContext, forceCompact, AutoCompactTrackingState } from "../compact/compact.js";
import { getSessionFilePath } from "../session/session.js";
import type { UsageAnchor } from "../compact/compact.js";
import { RecoveryState } from "../compact/recovery.js";
import { ContextTooLongError, RateLimitError } from "../llm/errors.js";
import { getOrCreatePlanPath, planExists } from "../plan-file/plan-file.js";
import { buildPlanModeReminder } from "../prompt/plan-mode.js";
import { applyBudget } from "../tool-result/budget.js";
import { buildManager } from "../tool-result/reconstruct.js";
import { ContentReplacementState } from "../tool-result/state.js";
import { readFile } from "node:fs/promises";
