import { Framework, State, registerThemeViews, type FrameworkConfig } from "@lark.js/docs"; // !!! For your project, it should be: from "@lark.js/docs"

// Auto-generated by defineConfig()
import { routes, docsConfig, loadContent, getSearchIndex } from "@lark-docs/generated";

// CSS
import "./main.css";

// === Register theme views ===

// === Register theme views ===
// Pass config so registerThemeViews selects the correct template mode
// (string vs VDOM) based on vdom. Must be called before Framework.boot()
// so views are registered when the default view is mounted during boot.
registerThemeViews({ vdom: false });

// === Inject site data + content loader into State ===

State.set({ docsConfig, loadContent, getSearchIndex });

// === Boot ===

const config: FrameworkConfig = {
  rootId: "app",
  routeMode: "history",
  routes,
  vdom: false,
  defaultPath: "/lark-cli/",
  // All /docs/* routes map to "theme/docs-layout" (see generated routes).
  // The layout stays mounted across navigation; observeLocation triggers
  // an async render that loads the matching .md content via loadContent.
  defaultView: "theme/docs-layout",
  unmatchedView: "theme/docs-layout",
  error(e: Error) {
    console.error("[lark-cli]", e);
  },
};

Framework.boot(config);
